name: build-and-test

on:
  push:
  pull_request:
  # run nightly to pick up any errors caused by changes in main geomesa
  schedule:
    - cron: '30 2 * * *' # 0230 UTC, 2130 EST

jobs:
  build-scala:
    runs-on: ubuntu-latest
    # avoid duplicate jobs on PRs from the main repo
    if: github.event_name == 'schedule' || github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'
      - name: Build with Maven
        run: mvn clean install -B -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false
      - name: Remove GeoMesa artifacts
        run: |
          rm -rf ~/.m2/repository/org/geomesa/example
